networks:
  zuma-network:
    driver: bridge
  proxy-nw:
    external: true

services:
  zuma-cache:
    image: redis:alpine
    container_name: zuma-redis
    ports:
      - "6379:6379"
    restart: always
    environment:
      - REDIS_CONNECTION=${REDIS_CONNECTION}

  zuma-redis-insight:
    image: redis/redisinsight:latest
    container_name: zuma-redis-insight
    ports:
      - "5540:5540"
    restart: always

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: zuma-npm
    restart: always
    ports: 
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-nw
      - zuma-network
  
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0
    container_name: aspire-dashboard
    environment:
      - ASPIRE_ALLOW_UNSECURED_TRANSPORT=true
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "18888:18888"
      - "4318:4317"
    networks:
      - proxy-nw
      - zuma-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: zuma-portainer
    restart: always
    ports:
      - "9443:9443" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-nw

  mailpit:
    image: axllent/mailpit
    container_name: zuma-mailpit
    restart: always
    networks:
      - zuma-network
      - proxy-nw

  seq:
    image: datalust/seq:latest
    container_name: zuma-seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_PASS}
      - SEQ_API_INGESTION_PORT_OTLP=4317
    ports:
      - 4317:4317
    volumes:
      - seq_data:/data
    networks:
      - proxy-nw
      - zuma-network

  zuma-db:
    image: postgres:latest
    container_name: zuma-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - zuma-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: zuma-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    networks:
      - zuma-network
      - proxy-nw

  zuma-api:
    container_name: zuma-api
    image: ghcr.io/tdohnal/zuma-api:latest
    restart: always
    depends_on:
      - zuma-db
      - rabbitmq
    networks:
      - zuma-network
      - proxy-nw
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ASPNETCORE_URLS=http://+:8080
      - GH_TOKEN=${GH_TOKEN}
      - SERILOG__SEQ__URL=http://zuma-seq:5341
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ASPNETCORE_HTTP_PORTS=8080 
      - ConnectionStrings__DbConnection=Host=zuma-db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS}
      - RABBITMQ__HOST=zuma-rabbitmq
      - RABBITMQ__USERNAME=${RABBIT_USER}
      - RABBITMQ__PASSWORD=${RABBIT_PASS} 
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    labels:
      - "dev.scalar.path=/docs/v1"

  communication-service:
    container_name: communication-service
    image: ghcr.io/tdohnal/communication-service:latest
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - zuma-network
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317
      - GH_TOKEN=${GH_TOKEN}
      - SERILOG__SEQ__URL=http://zuma-seq:5341
      - RABBITMQ__HOST=zuma-rabbitmq
      - RABBITMQ__USERNAME=${RABBIT_USER}
      - RABBITMQ__PASSWORD=${RABBIT_PASS}
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ConnectionStrings__DbConnection=Host=zuma-db;Port=5432;Database=zuma-communication;Username=${DB_USER};Password=${DB_PASS}
      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASS}
      - Smtp__SenderEmail=${SMTP_SENDER}
      - Smtp__SenderName=${SMTP_SENDER_NAME}

  customer-service:
    container_name: customer-service
    image: ghcr.io/tdohnal/customer-service:latest
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - zuma-network
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317
      - SERILOG__SEQ__URL=http://zuma-seq:5341
      - RABBITMQ__HOST=zuma-rabbitmq
      - RABBITMQ__USERNAME=${RABBIT_USER}
      - RABBITMQ__PASSWORD=${RABBIT_PASS}
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ConnectionStrings__DbConnection=Host=zuma-db;Port=5432;Database=zuma-customer;Username=${DB_USER};Password=${DB_PASS}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}

  pgadmin:
    image: dpage/pgadmin4
    container_name: zuma-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    networks:
      - zuma-network
      - proxy-nw
    depends_on:
      - zuma-db

volumes:
  postgres_data:
  seq_data:
  portainer_data: