services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: zuma-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=zuma_admin
      - RABBITMQ_DEFAULT_PASS=moje_tajne_heslo_123
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI

  communication-service:
    build:
      context: .
      dockerfile: ZUMA.CommunicationService/Dockerfile
    container_name: communication-service
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development

  customer-service:
    build:
      context: .
      dockerfile: ZUMA.CustomerService/Dockerfile
    container_name: customer-service
    depends_on:
      - rabbitmq
    ports:
      - "8082:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development

  zuma.api:
    build:
      context: .
      dockerfile: ZUMA.API/Dockerfile
    container_name: zuma-api
    ports:
      - "8080:8080"
    depends_on:
      - zuma-db
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # TADY SE ZMĚNÍ CONNECTION STRING V APP (předpokládám, že ho bereš z ENV)
      - ConnectionStrings__PostgresConnection=Host=zuma-db;Database=zuma_db;Username=postgres;Password=ZumaPostgresPassword2026!
    restart: always

  zuma-db:
    image: postgres:latest
    container_name: zuma-db
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ZumaPostgresPassword2026!
      - POSTGRES_DB=zuma_db
    ports:
      - "5432:5432" # Standardní Postgres port

  # BONUS: Webové rozhraní pro DB (něco jako SQL Management Studio, ale v prohlížeči)
  pgadmin:
    image: dpage/pgadmin4
    container_name: zuma-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@zuma.cz
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - zuma-db

volumes:
  postgres_data: