networks:
  zuma-network:
    driver: bridge
  proxy-nw:
    external: true

services:
  mailpit:
    image: axllent/mailpit
    container_name: zuma-mailpit
    networks:
      - zuma-network
      - proxy-nw
    ports:
      - "8025:8025" # Webové rozhraní (tady uvidíš maily)
      - "1025:1025" # SMTP port
    restart: always

  seq:
    image: datalust/seq:latest
    container_name: zuma-seq
    ports:
      - "8090:80"    # Používáme tvůj volný port
      - "5341:5341"  # Port pro příjem logů
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_PASS}
    restart: unless-stopped
    networks:
      - proxy-nw
    volumes:
      - seq_data:/data

  zuma-db:
    image: postgres:latest
    container_name: zuma-db
    networks:
      - zuma-network
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS} # Tady musí být celý název PASSWORD
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: zuma-rabbitmq
    networks:
      - zuma-network
      - proxy-nw
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS} # Tady stačí PASS, Rabbit to zná
    ports:
      - "5672:5672"
      - "15672:15672"

  zuma-api:
    container_name: zuma-api
    networks:
      - zuma-network
      - proxy-nw
    depends_on:
      - zuma-db
      - rabbitmq
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GH_TOKEN=${GH_TOKEN}
      - SERILOG__SEQ__URL=http://seq:5341
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ASPNETCORE_HTTP_PORTS=8080 
      - ConnectionStrings__DbConnection=Host=zuma-db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS}
      - RABBITMQ__HOST=${RABBIT_HOST}
      - RABBITMQ__USERNAME=${RABBIT_USER}
      - RABBITMQ__PASSWORD=${RABBIT_PASS} # .NET pravděpodobně chce "Password"
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    labels:
      - "dev.scalar.path=/docs/v1"

  communication-service:
    container_name: communication-service
    networks:
      - zuma-network
      - proxy-nw
    depends_on:
      - rabbitmq
    restart: always
    environment:
      - GH_TOKEN=${GH_TOKEN}
      - SERILOG__SEQ__URL=http://seq:5341
      - RABBITMQ__HOST=${RABBIT_HOST}
      - RABBITMQ__USERNAME=${RABBIT_USER}
      - RABBITMQ__PASSWORD=${RABBIT_PASS}
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ConnectionStrings__DbConnection=Host=zuma-db;Port=5432;Database=zuma-communication;Username=${DB_USER};Password=${DB_PASS}
     # SMTP sekce pro Brevo - Musí sedět na SmtpOptions.cs
      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASS}
      - Smtp__SenderEmail=${SMTP_SENDER}
      - Smtp__SenderName=${SMTP_SENDER_NAME}

  customer-service:
    container_name: customer-service
    networks:
      - zuma-network
      - proxy-nw
    depends_on:
      - rabbitmq
    restart: always
    environment:

      - SERILOG__SEQ__URL=http://seq:5341
      - RABBITMQ__HOST=${RABBIT_HOST}
      - RABBITMQ__USERNAME=${RABBIT_USER}
      - RABBITMQ__PASSWORD=${RABBIT_PASS}
      - ASPNETCORE_ENVIRONMENT=${APP_ENV}
      - ConnectionStrings__DbConnection=Host=zuma-db;Port=5432;Database=zuma-customer;Username=${DB_USER};Password=${DB_PASS}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}

  pgadmin:
    image: dpage/pgadmin4
    container_name: zuma-pgadmin
    networks:
      - zuma-network
      - proxy-nw
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS} # pgAdmin chce taky PASSWORD
    ports:
      - "5050:80"
    depends_on:
      - zuma-db

volumes:
  postgres_data:
  seq_data: