using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace ZUMA.API.Mapping;

// Pomocný model pro vlastnosti, aby byl MappingModel čistý
internal record PropertyMapping(string Name);

// Hlavní model pro generování - musí být record kvůli rovnosti
internal record MappingModel(
    string Namespace,
    string DtoName,
    string EntityFullName,
    string EntityName,
    ImmutableArray<PropertyMapping> Properties);

[Generator]
public sealed class MappingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Filtrování a transformace syntaxe na náš model
        var mappingModels = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetMappingTarget(ctx))
            .Where(static m => m is not null);

        // 2. Registrace výstupu
        context.RegisterSourceOutput(mappingModels, static (ctx, model) =>
        {
            if (model is null) return;
            var source = GenerateMappingCode(model);
            ctx.AddSource($"{model.DtoName}.Mapping.g.cs", source);
        });
    }

    private static MappingModel? GetMappingTarget(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not ClassDeclarationSyntax classSyntax)
            return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
        if (symbol == null) return null;

        // Hledání atributu [GenerateMapping(typeof(TargetEntity))]
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "GenerateMappingAttribute" ||
                                 a.AttributeClass?.Name == "GenerateMapping");

        if (attr == null || attr.ConstructorArguments.Length == 0) return null;

        var targetType = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
        if (targetType == null) return null;

        // Analýza vlastností - hledáme shodu jmen a typů
        var dtoProps = symbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.SetMethod != null);

        var entityProps = targetType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.SetMethod != null)
            .ToDictionary(p => p.Name, p => p);

        var matchedProperties = new List<PropertyMapping>();

        foreach (var dProp in dtoProps)
        {
            if (entityProps.TryGetValue(dProp.Name, out var ePropSymbol))
            {
                var eProp = (IPropertySymbol)ePropSymbol!;
                // Kontrola, zda jsou typy stejné
                if (SymbolEqualityComparer.Default.Equals(dProp.Type, eProp.Type))
                {
                    matchedProperties.Add(new PropertyMapping(dProp.Name));
                }
            }
        }

        return new MappingModel(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            targetType.ToDisplayString(), // Celý název včetně namespace
            targetType.Name,
            matchedProperties.ToImmutableArray()
        );
    }

    private static string GenerateMappingCode(MappingModel model)
    {
        var sb = new StringBuilder();

        sb.Append($@"// <auto-generated />
using System;

namespace {model.Namespace};

public static partial class {model.DtoName}MappingExtensions
{{
    public static {model.DtoName} ToDto(this {model.EntityFullName} entity)
    {{
        if (entity is null) return null!;

        return new {model.DtoName}
        {{
");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"            {prop.Name} = entity.{prop.Name},");
        }

        sb.Append($@"        }};
    }}

    public static {model.EntityFullName} ToEntity(this {model.DtoName} dto)
    {{
        if (dto is null) return null!;

        return new {model.EntityFullName}
        {{
");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"            {prop.Name} = dto.{prop.Name},");
        }

        sb.Append(@"        };
    }
}");
        return sb.ToString();
    }
}