#pragma warning RS1038 

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace ZUMA.API.Mapping;

[Microsoft.CodeAnalysis.Generator]
public sealed class MappingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetMappingTarget(ctx))
            .Where(m => m != null);

        context.RegisterSourceOutput(classes, (ctx, model) =>
        {
            if (model is null) return;
            var source = GenerateMappingCode(model);
            ctx.AddSource($"{model.DtoName}.Mapping.g.cs", source);
        });
    }

    private static string GenerateMappingCode(MappingModel model)
    {
        var dtoProps = model.DtoSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.SetMethod != null);

        var entityProps = model.EntitySymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.SetMethod != null)
            .ToDictionary(p => p.Name);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"using ZUMA.BussinessLogic.Entities.Customer;");
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.DtoName}MappingExtensions");
        sb.AppendLine("{");

        // ToDto
        sb.AppendLine($"    public static {model.DtoName} ToDto(this {model.EntityName} entity) => new {model.DtoName}");
        sb.AppendLine("    {");
        foreach (var prop in dtoProps)
        {
            if (entityProps.TryGetValue(prop.Name, out var entityProp) &&
                SymbolEqualityComparer.Default.Equals(prop.Type, entityProp.Type))
            {
                sb.AppendLine($"        {prop.Name} = entity.{prop.Name},");
            }
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // ToEntity
        sb.AppendLine($"    public static {model.EntityName} ToEntity(this {model.DtoName} dto) => new {model.EntityName}");
        sb.AppendLine("    {");
        foreach (var prop in dtoProps)
        {
            if (entityProps.ContainsKey(prop.Name))
            {
                sb.AppendLine($"        {prop.Name} = dto.{prop.Name},");
            }
        }
        sb.AppendLine("    };");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static MappingModel? GetMappingTarget(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not ClassDeclarationSyntax classSyntax)
            return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classSyntax);
        if (symbol == null) return null;

        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == nameof(GenerateMappingAttribute));
        if (attr == null) return null;

        var targetType = attr.ConstructorArguments[0].Value as ITypeSymbol;
        if (targetType == null) return null;

        var dtoType = symbol as ITypeSymbol;
        if (dtoType == null) return null;

        return MappingModel.Create(dtoType, targetType);

    }

    internal sealed class MappingModel
    {
        public ITypeSymbol DtoSymbol { get; }
        public ITypeSymbol EntitySymbol { get; }

        public string DtoName => DtoSymbol.Name;
        public string EntityName => EntitySymbol.Name;
        public string Namespace => DtoSymbol.ContainingNamespace.ToDisplayString();

        private MappingModel(ITypeSymbol dto, ITypeSymbol entity)
        {
            DtoSymbol = dto;
            EntitySymbol = entity;
        }

        public static MappingModel Create(ITypeSymbol dto, ITypeSymbol entity)
            => new(dto, entity);
    }
}
