// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZUMA.CustomerService.Infrastructure.Persistence;

#nullable disable

namespace ZUMA.CustomerService.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260412153438_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.ControlElementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListType")
                        .HasColumnType("integer");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("UserControlElements", (string)null);
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.ControlElementsItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ControlElementId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ControlElementId");

                    b.ToTable("ControlElementsItems", (string)null);
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.RegistrationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationCodeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("IX_Registrations_Deleted");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Registrations", "public");
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthCode")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime?>("AuthCodeExpiration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("IX_Users_Deleted");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.ControlElementEntity", b =>
                {
                    b.OwnsOne("ZUMA.CustomerService.Domain.ValueObjects.ElementsPermission", "ElementsPermission", b1 =>
                        {
                            b1.Property<long>("ControlElementEntityId");

                            b1.HasKey("ControlElementEntityId");

                            b1.ToTable("UserControlElements");

                            b1
                                .ToJson("ElementsPermission")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ControlElementEntityId");

                            b1.OwnsMany("ZUMA.CustomerService.Domain.ValueObjects.ElementsUserPermission", "UserPermissions", b2 =>
                                {
                                    b2.Property<long>("ElementsPermissionControlElementEntityId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("CanDelete");

                                    b2.Property<long>("CanEdit");

                                    b2.Property<long>("CanView");

                                    b2.Property<long>("UserId");

                                    b2.HasKey("ElementsPermissionControlElementEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("UserControlElements");

                                    b2.WithOwner()
                                        .HasForeignKey("ElementsPermissionControlElementEntityId");
                                });

                            b1.Navigation("UserPermissions");
                        });

                    b.Navigation("ElementsPermission")
                        .IsRequired();
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.ControlElementsItemEntity", b =>
                {
                    b.HasOne("ZUMA.CustomerService.Domain.Entities.ControlElementEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("ControlElementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.RegistrationEntity", b =>
                {
                    b.HasOne("ZUMA.CustomerService.Domain.Entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("ZUMA.CustomerService.Domain.Entities.RegistrationEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.UserEntity", b =>
                {
                    b.OwnsOne("ZUMA.CustomerService.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<long>("UserEntityId");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("ZipCode")
                                .IsRequired();

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users", "public");

                            b1
                                .ToJson("Address")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ZUMA.CustomerService.Domain.Entities.ControlElementEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
