name: Deploy to host

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and restart Docker locally
      bash: powershell -ExecutionPolicy Bypass -Command "{0}"
      env:
        # Tady vytáhneme tajný token ze secrets do proměnné prostředí workflow
        MY_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE

        if [ $(docker ps -aq -f name=mk-app) ]; then
          echo "Stopping and removing old container..."
          docker stop mk-app || true
          docker rm mk-app || true
        fi

        echo "Building Docker image..."
        # PŘIDÁNO: --build-arg posílá token do Dockerfile
        docker build --build-arg GH_TOKEN=${{ secrets.NUGET_GITHUB_TOKEN }} -t eshop_mk .

        echo "Starting Docker container..."
        docker run -d --restart always --name mk-app -p 5000:80 eshop_mk

    - name: Verify container is running
      run: docker ps
