name: Deploy to host

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and restart Docker locally
      shell: bash
      env:
        # Definice tokenu pro použití uvnitř scriptu
        MY_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}
      run: |
        # Přejdeme do pracovního adresáře (volitelné, obvykle tam už jsi)
        cd "$GITHUB_WORKSPACE"

        # 1. Odstranění starého kontejneru, pokud existuje
        if [ "$(docker ps -aq -f name=mk-app)" ]; then
          echo "Stopping and removing old container..."
          docker stop mk-app || true
          docker rm mk-app || true
        fi

        # 2. Build obrazu s předáním tokenu (pro privátní NuGet balíčky)
        echo "Building Docker image..."
        docker build --build-arg GH_TOKEN="${MY_TOKEN}" -t eshop_mk .

        # 3. Spuštění nového kontejneru
        echo "Starting Docker container..."
        docker run -d --restart always --name mk-app -p 5000:80 eshop_mk

    - name: Verify container is running
      run: docker ps
