name: CI - Build, Test and Coverage

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: ZUMA
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Add NuGet Source and Auth
      # Nejdřív smažeme případný existující zdroj "GitHub", aby add source nehodil chybu
      run: |
        dotnet nuget remove source "GitHub" || true
        dotnet nuget add source "https://nuget.pkg.github.com/tdohnal/index.json" --name "GitHub" --username "tdohnal" --password "${{ secrets.NUGET_GITHUB_TOKEN }}" --store-password-in-clear-text
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}

    - name: Restore
      run: dotnet restore "ZUMA.API.slnx"
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}

    - name: Build
      run: dotnet build "ZUMA.API.slnx" --no-restore

    - name: Run all tests
      run: |
          find Tests -name "*.csproj" | while read project_file; do
            # Vytvoříme unikátní název podle jména projektu
            project_name=$(basename "$project_file" .csproj)
            echo "Running tests for $project_name"
            dotnet test "$project_file" --no-build --verbosity normal \
              /p:CollectCoverage=true \
              /p:CoverletOutputFormat=cobertura \
              /p:CoverletOutput=./TestResults/$project_name.xml
          done
          
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        # Použijeme hvězdičku pro nalezení všech xml reportů v rootu složky
        files: ${{ github.workspace }}/TestResults/*.xml
        fail_ci_if_error: true
        verbose: true
