name: CI - Build, Test and Coverage

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN }} 

    - name: Restore
      run: dotnet restore "ZUMA.API.slnx" --interactive
      env:
        # Tohle vnutí dotnetu použití tvého secretu pro GitHub Packages
        NUGET_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN }}

    - name: Build
      run: dotnet build "ZUMA.API.slnx" --no-restore

    - name: Test with Coverage
      # Generujeme cobertura.xml pro Codecov
      run: |
        dotnet test "ZUMA.API.slnx" --no-build --verbosity normal \
        /p:CollectCoverage=true \
        /p:CoverletOutputFormat=cobertura \
        /p:CoverletOutput=./TestResults/ \
        --p:Exclude="[ZUMA.*.Migrations]*;[ZUMA.*]*.Program;[ZUMA.*.DTOs]*"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
